name: BankFlowCRM Backend CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Display .NET version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore BankFlowCRM.slnx

      - name: Build solution
        run: dotnet build BankFlowCRM.slnx --configuration Release --no-restore

      - name: Run tests
        run: dotnet test BankFlowCRM.slnx --configuration Release --no-build
