name: BankFlowCRM Backend CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Display .NET version
        run: dotnet --version

      - name: Restore IdentityService
        run: dotnet restore IdentityService/IdentityService.csproj

      - name: Restore CustomerService
        run: dotnet restore CustomerService/CustomerService.csproj

      - name: Build IdentityService
        run: dotnet build IdentityService/IdentityService.csproj --configuration Release --no-restore

      - name: Build CustomerService
        run: dotnet build CustomerService/CustomerService.csproj --configuration Release --no-restore
